# Copyright 2022 Neuraville, LLC. All Rights Reserved.

genome = {
    "version": "2.0",
    "max_burst_count": 3,
    "burst_delay": 0.1,
    "evolution_burst_count": 50,
    "neuron_morphologies": {
        "placeholder": {},
        "block_to_block": {
            "vectors": [[0, 0, 0]]
        },
        "block_to_block4": {
            "vectors": [[0, 0, 4]]
        },
        "decrease_filter_diagonal": {
            "vectors": [[0, 1, 1]]
        },
        "increase_filter_diagonal": {
            "vectors": [[0, 1, -1]]
        },
        "lateral_+x": {
            "vectors": [[1, 0, 0]]
        },
        "lateral_-x": {
            "vectors": [[-1, 0, 0]]
        },
        "lateral_+y": {
            "vectors": [[0, 1, 0]]
        },
        "lateral_-y": {
            "vectors": [[0, -1, 0]]
        },
        "lateral_+z": {
            "vectors": [[0, 0, 1]]
        },
        "lateral_-z": {
            "vectors": [[0, 0, -1]]
        },
        "reducer_x": {
            "functions": True
        },
        "randomizer": {
            "functions": True
        },
        "to_first_block": {
            "patterns": [[["*", "*", "*"], [0, 0, 0]]]
        },
        "Move_Forward_Targ": {
            "patterns": [[[0, 0, 4], [0, 0, 0]],
                        [[2, 0, 4], [1, 0, 0]],
                        [[4, 0, 4], [2, 0, 0]],
                        [[6, 0, 4], [3, 0, 0]]]
        },
        "Move_Backward_Targ": {
            "patterns": [[[1, 0, 4], [0, 0, 0]],
                        [[3, 0, 4], [1, 0, 0]],
                        [[5, 0, 4], [2, 0, 0]],
                        [[7, 0, 4], [3, 0, 0]]]
        },
        "one_to_all": {
            "patterns": [[[0, 0, 0], ["*", "*", "*"]]]
        },
        "to_forward": {
            "patterns":[[[0, 0, 0], [0, 0, 0]],
                        [[0, 0, 0], [2, 0, 0]],
                        [[0, 0, 0], [4, 0, 0]],
                        [[0, 0, 0], [6, 0, 0]]]
        }, 
        "block_connection": {
            "functions": True
        }
    },
    "species": {
        "parents": {},
        "species_id": "",
        "class": "toy",
        "brand": "gazebo",
        "model": "smart_car"
    },
    "blueprint": {
        "_____10b-_____s-__-__name-t":  "smart_car",
       
        "_____10c-o_init-cx-__name-t": "position_init_opu",
        "_____10c-o_init-cx-_group-t": "OPU",
        "_____10c-o_init-cx-_n_cnt-i": 1,
        "_____10c-o_init-nx-gd_vis-b": True,
        "_____10c-o_init-nx-rcordx-i": 15,
        "_____10c-o_init-nx-rcordy-i": 7,
        "_____10c-o_init-nx-rcordz-i": 10,
        "_____10c-o_init-nx-___bbx-i": 1,
        "_____10c-o_init-nx-___bby-i": 1,
        "_____10c-o_init-nx-___bbz-i": 1,
        "_____10c-o_init-cx-synatt-i": 100,
        "_____10c-o_init-cx-pstcr_-f": 0,
        "_____10c-o_init-cx-pstcrm-f": 500,
        "_____10c-o_init-cx-plst_c-f": 5,
        "_____10c-o_init-nx-fire_t-f": 1500,
        "_____10c-o_init-nx-refrac-i": 0,
        "_____10c-o_init-nx-leak_c-f": 2000,
        "_____10c-o_init-nx-c_fr_c-i": 1,
        "_____10c-o_init-nx-snooze-f": 0,
        "_____10c-o_init-cx-dstmap-d": {},
       
        "_____10c-i_mPre-cx-__name-t": "motor_Preference",
        "_____10c-i_mPre-cx-_group-t": "IPU",
        "_____10c-i_mPre-cx-_n_cnt-i": 1,
        "_____10c-i_mPre-nx-gd_vis-b": True,
        "_____10c-i_mPre-nx-rcordx-i": 15,
        "_____10c-i_mPre-nx-rcordy-i": 7,
        "_____10c-i_mPre-nx-rcordz-i": 10,
        "_____10c-i_mPre-nx-___bbx-i": 1,
        "_____10c-i_mPre-nx-___bby-i": 1,
        "_____10c-i_mPre-nx-___bbz-i": 1,
        "_____10c-i_mPre-cx-synatt-i": 100,
        "_____10c-i_mPre-cx-pstcr_-f": 0,
        "_____10c-i_mPre-cx-pstcrm-f": 500,
        "_____10c-i_mPre-cx-plst_c-f": 5,
        "_____10c-i_mPre-nx-fire_t-f": 1500,
        "_____10c-i_mPre-nx-refrac-i": 0,
        "_____10c-i_mPre-nx-leak_c-f": 2000,
        "_____10c-i_mPre-nx-c_fr_c-i": 1,
        "_____10c-i_mPre-nx-snooze-f": 0,
        "_____10c-i_mPre-cx-de_gen-f": 0,
        "_____10c-i_mPre-cx-dstmap-d": {"t_mTha": [["to_forward", [1, 1, 1], 1, True]]},

        "_____10c-t_mFor-cx-__name-t": "forward_thalamus",
        "_____10c-t_mFor-cx-_group-t": "thalamus",
        "_____10c-t_mFor-cx-_n_cnt-i": 1,
        "_____10c-t_mFor-nx-gd_vis-b": True,
        "_____10c-t_mFor-nx-rcordx-i": 9,
        "_____10c-t_mFor-nx-rcordy-i": 5,
        "_____10c-t_mFor-nx-rcordz-i": 5,
        "_____10c-t_mFor-nx-___bbx-i": 4,
        "_____10c-t_mFor-nx-___bby-i": 1,
        "_____10c-t_mFor-nx-___bbz-i": 1,
        "_____10c-t_mFor-cx-synatt-i": 100,
        "_____10c-t_mFor-cx-pstcr_-f": 500,
        "_____10c-t_mFor-cx-pstcrm-f": 35,
        "_____10c-t_mFor-cx-plst_c-f": 5,
        "_____10c-t_mFor-nx-fire_t-f": 1,
        "_____10c-t_mFor-nx-refrac-i": 0,
        "_____10c-t_mFor-nx-leak_c-f": 1,
        "_____10c-t_mFor-nx-c_fr_c-i": 3,
        "_____10c-t_mFor-nx-snooze-f": 0,
        "_____10c-t_mFor-cx-de_gen-f": 0,
        "_____10c-t_mFor-cx-dstmap-d": {"i_mPre": [["to_first_block", [1, 1, 1], 1, False]]},

        "_____10c-t_mBck-cx-__name-t": "backward_thalamus",
        "_____10c-t_mBck-cx-_group-t": "thalamus",
        "_____10c-t_mBck-cx-_n_cnt-i": 1,
        "_____10c-t_mBck-nx-gd_vis-b": True,
        "_____10c-t_mBck-nx-rcordx-i": 9,
        "_____10c-t_mBck-nx-rcordy-i": 5,
        "_____10c-t_mBck-nx-rcordz-i": 10,
        "_____10c-t_mBck-nx-___bbx-i": 4,
        "_____10c-t_mBck-nx-___bby-i": 1,
        "_____10c-t_mBck-nx-___bbz-i": 1,
        "_____10c-t_mBck-cx-synatt-i": 100,
        "_____10c-t_mBck-cx-pstcr_-f": 2000,
        "_____10c-t_mBck-cx-pstcrm-f": 35,
        "_____10c-t_mBck-cx-plst_c-f": 5,
        "_____10c-t_mBck-nx-fire_t-f": 1,
        "_____10c-t_mBck-nx-refrac-i": 0,
        "_____10c-t_mBck-nx-leak_c-f": 1,
        "_____10c-t_mBck-nx-c_fr_c-i": 3,
        "_____10c-t_mBck-nx-snooze-f": 0,
        "_____10c-t_mBck-cx-de_gen-f": 0,
        "_____10c-t_mBck-cx-dstmap-d": {"i_mPre": [["to_first_block", [1, 1, 1], -1, False]]},

        "_____10c-i__mot-cx-__name-t": "motor_ipu",
        "_____10c-i__mot-cx-_group-t": "IPU",
        "_____10c-i__mot-cx-_n_cnt-i": 1,
        "_____10c-i__mot-nx-gd_vis-b": True,
        "_____10c-i__mot-nx-rcordx-i": 0,
        "_____10c-i__mot-nx-rcordy-i": 5,
        "_____10c-i__mot-nx-rcordz-i": 10,
        "_____10c-i__mot-nx-___bbx-i": 8,
        "_____10c-i__mot-nx-___bby-i": 1,
        "_____10c-i__mot-nx-___bbz-i": 10,
        "_____10c-i__mot-cx-synatt-i": 100,
        "_____10c-i__mot-cx-pstcr_-f": 500,
        "_____10c-i__mot-cx-pstcrm-f": 35,
        "_____10c-i__mot-cx-plst_c-f": 5,
        "_____10c-i__mot-nx-fire_t-f": 1,
        "_____10c-i__mot-nx-refrac-i": 0,
        "_____10c-i__mot-nx-leak_c-f": 1,
        "_____10c-i__mot-nx-c_fr_c-i": 3,
        "_____10c-i__mot-nx-snooze-f": 0,
        "_____10c-i__mot-cx-de_gen-f": 0,
        "_____10c-i__mot-cx-dstmap-d": {"t_mFor": [["Move_Forward_Targ", [1, 1, 1], 1, False]],
                                        "t_mBck": [["Move_Backward_Targ", [1, 1, 1], 1, False]]},

        "_____10c-o__mot-cx-__name-t": "motor_opu",
        "_____10c-o__mot-cx-_group-t": "OPU",
        "_____10c-o__mot-cx-_n_cnt-i": 1,
        "_____10c-o__mot-nx-gd_vis-b": True,
        "_____10c-o__mot-nx-rcordx-i": 0,
        "_____10c-o__mot-nx-rcordy-i": 10,
        "_____10c-o__mot-nx-rcordz-i": 10,
        "_____10c-o__mot-nx-___bbx-i": 8,
        "_____10c-o__mot-nx-___bby-i": 1,
        "_____10c-o__mot-nx-___bbz-i": 10,
        "_____10c-o__mot-cx-synatt-i": 100,
        "_____10c-o__mot-cx-pstcr_-f": 500,
        "_____10c-o__mot-cx-pstcrm-f": 35,
        "_____10c-o__mot-cx-plst_c-f": 0.05,
        "_____10c-o__mot-nx-fire_t-f": 1,
        "_____10c-o__mot-nx-refrac-i": 0,
        "_____10c-o__mot-nx-leak_c-f": 0,
        "_____10c-o__mot-nx-c_fr_c-i": 3,
        "_____10c-o__mot-nx-snooze-f": 0,
        "_____10c-o__mot-cx-de_gen-f": 0,
        "_____10c-o__mot-cx-dstmap-d": {"i__mot": [["block_to_block", [1, 1, 1], 1, False]]},

        "_____10c-t_pmot-cx-__name-t": "Premotor_Cortex",
        "_____10c-t_pmot-cx-_group-t": "thalamus",
        "_____10c-t_pmot-cx-_n_cnt-i": 1,
        "_____10c-t_pmot-nx-gd_vis-b": True,
        "_____10c-t_pmot-nx-rcordx-i": 0,
        "_____10c-t_pmot-nx-rcordy-i": 15,
        "_____10c-t_pmot-nx-rcordz-i": 15,
        "_____10c-t_pmot-nx-___bbx-i": 8,
        "_____10c-t_pmot-nx-___bby-i": 1,
        "_____10c-t_pmot-nx-___bbz-i": 1,
        "_____10c-t_pmot-cx-synatt-i": 100,
        "_____10c-t_pmot-cx-pstcr_-f": 500,
        "_____10c-t_pmot-cx-pstcrm-f": 35,
        "_____10c-t_pmot-cx-plst_c-f": 0.05,
        "_____10c-t_pmot-nx-fire_t-f": 1,
        "_____10c-t_pmot-nx-refrac-i": 0,
        "_____10c-t_pmot-nx-leak_c-f": 0,
        "_____10c-t_pmot-nx-c_fr_c-i": 3,
        "_____10c-t_pmot-nx-snooze-f": 0,
        "_____10c-t_pmot-cx-de_gen-f": 0,
        "_____10c-t_pmot-cx-dstmap-d": {"o__mot": [["block_to_block4", [1, 1, 1], 1, False]]},

        "_____10c-t_mTha-cx-__name-t": "Motor Thalamus",
        "_____10c-t_mTha-cx-_group-t": "thalamus",
        "_____10c-t_mTha-cx-_n_cnt-i": 1,
        "_____10c-t_mTha-nx-gd_vis-b": True,
        "_____10c-t_mTha-nx-rcordx-i": 0,
        "_____10c-t_mTha-nx-rcordy-i": 15,
        "_____10c-t_mTha-nx-rcordz-i": 7,
        "_____10c-t_mTha-nx-___bbx-i": 8,
        "_____10c-t_mTha-nx-___bby-i": 1,
        "_____10c-t_mTha-nx-___bbz-i": 1,
        "_____10c-t_mTha-cx-synatt-i": 100,
        "_____10c-t_mTha-cx-pstcr_-f": 500,
        "_____10c-t_mTha-cx-pstcrm-f": 35,
        "_____10c-t_mTha-cx-plst_c-f": 0.05,
        "_____10c-t_mTha-nx-fire_t-f": 10,
        "_____10c-t_mTha-nx-refrac-i": 0,
        "_____10c-t_mTha-nx-leak_c-f": 0,
        "_____10c-t_mTha-nx-c_fr_c-i": 3,
        "_____10c-t_mTha-nx-snooze-f": 0,
        "_____10c-t_mTha-cx-de_gen-f": 0,
        "_____10c-t_mTha-cx-dstmap-d": {"t_pmot": [["block_to_block", [1, 1, 1], 1, False]]},

        "_____10c-t_bDec-cx-__name-t": "Babbler Decoder",
        "_____10c-t_bDec-cx-_group-t": "thalamus",
        "_____10c-t_bDec-cx-_n_cnt-i": 1,
        "_____10c-t_bDec-nx-gd_vis-b": True,
        "_____10c-t_bDec-nx-rcordx-i": 0,
        "_____10c-t_bDec-nx-rcordy-i": 15,
        "_____10c-t_bDec-nx-rcordz-i": 0,
        "_____10c-t_bDec-nx-___bbx-i": 8,
        "_____10c-t_bDec-nx-___bby-i": 1,
        "_____10c-t_bDec-nx-___bbz-i": 1,
        "_____10c-t_bDec-cx-synatt-i": 100,
        "_____10c-t_bDec-cx-pstcr_-f": 50,
        "_____10c-t_bDec-cx-pstcrm-f": 35,
        "_____10c-t_bDec-cx-plst_c-f": 0.05,
        "_____10c-t_bDec-nx-fire_t-f": 1,
        "_____10c-t_bDec-nx-refrac-i": 0,
        "_____10c-t_bDec-nx-leak_c-f": 0,
        "_____10c-t_bDec-nx-c_fr_c-i": 3,
        "_____10c-t_bDec-nx-snooze-f": 0,
        "_____10c-t_bDec-cx-de_gen-f": 5,
        "_____10c-t_bDec-cx-dstmap-d": {"t_mTha": [["block_to_block", [1, 1, 1], 1, False]]},

        "_____10c-t_mbab-cx-__name-t": "motor_babbler",
        "_____10c-t_mbab-cx-_group-t": "thalamus",
        "_____10c-t_mbab-cx-_n_cnt-i": 1,
        "_____10c-t_mbab-nx-gd_vis-b": True,
        "_____10c-t_mbab-nx-rcordx-i": -125,
        "_____10c-t_mbab-nx-rcordy-i": 20,
        "_____10c-t_mbab-nx-rcordz-i": 0,
        "_____10c-t_mbab-nx-___bbx-i": 256,
        "_____10c-t_mbab-nx-___bby-i": 1,
        "_____10c-t_mbab-nx-___bbz-i": 1,
        "_____10c-t_mbab-cx-synatt-i": 100,
        "_____10c-t_mbab-cx-pstcr_-f": 50,
        "_____10c-t_mbab-cx-pstcrm-f": 35,
        "_____10c-t_mbab-cx-plst_c-f": 0.05,
        "_____10c-t_mbab-nx-fire_t-f": 1,
        "_____10c-t_mbab-nx-refrac-i": 0,
        "_____10c-t_mbab-nx-leak_c-f": 0,
        "_____10c-t_mbab-nx-c_fr_c-i": 10,
        "_____10c-t_mbab-nx-snooze-f": 0,
        "_____10c-t_mbab-cx-de_gen-f": 0,
        "_____10c-t_mbab-cx-dstmap-d": {"t_bDec": [["reducer_x", [1, 1, 1], 1, False]]},

        "_____10c-t_mbbb-cx-__name-t": "prebabble",
        "_____10c-t_mbbb-cx-_group-t": "thalamus",
        "_____10c-t_mbbb-cx-_n_cnt-i": 1,
        "_____10c-t_mbbb-nx-gd_vis-b": True,
        "_____10c-t_mbbb-nx-rcordx-i": -125,
        "_____10c-t_mbbb-nx-rcordy-i": 25,
        "_____10c-t_mbbb-nx-rcordz-i": 0,
        "_____10c-t_mbbb-nx-___bbx-i": 2560,
        "_____10c-t_mbbb-nx-___bby-i": 1,
        "_____10c-t_mbbb-nx-___bbz-i": 1,
        "_____10c-t_mbbb-cx-synatt-i": 100,
        "_____10c-t_mbbb-cx-pstcr_-f": 50,
        "_____10c-t_mbbb-cx-pstcrm-f": 35,
        "_____10c-t_mbbb-cx-plst_c-f": 0.05,
        "_____10c-t_mbbb-nx-fire_t-f": 1,
        "_____10c-t_mbbb-nx-refrac-i": 2560,
        "_____10c-t_mbbb-nx-leak_c-f": 0,
        "_____10c-t_mbbb-nx-c_fr_c-i": 3,
        "_____10c-t_mbbb-nx-snooze-f": 0,
        "_____10c-t_mbbb-cx-de_gen-f": 0,
        "_____10c-t_mbbb-cx-dstmap-d": {"t_mbbb": [["lateral_+x", [1, 1, 1], 1, False]],
                                        "t_mbab": [["block_connection", [1, 1, 1], 1, False]]},
        
        "_____10c-i__bat-cx-__name-t": "battery_ipu",
        "_____10c-i__bat-cx-_group-t": "IPU",
        "_____10c-i__bat-cx-_n_cnt-i": 1,
        "_____10c-i__bat-nx-gd_vis-b": True,
        "_____10c-i__bat-nx-rcordx-i": -3,
        "_____10c-i__bat-nx-rcordy-i": 15,
        "_____10c-i__bat-nx-rcordz-i": 0,
        "_____10c-i__bat-nx-___bbx-i": 1,
        "_____10c-i__bat-nx-___bby-i": 1,
        "_____10c-i__bat-nx-___bbz-i": 10,
        "_____10c-i__bat-cx-synatt-i": 100,
        "_____10c-i__bat-cx-pstcr_-f": 50000,
        "_____10c-i__bat-cx-pstcrm-f": 35,
        "_____10c-i__bat-cx-plst_c-f": 0.05,
        "_____10c-i__bat-nx-fire_t-f": 1,
        "_____10c-i__bat-nx-refrac-i": 0,
        "_____10c-i__bat-nx-leak_c-f": 0,
        "_____10c-i__bat-nx-c_fr_c-i": 3,
        "_____10c-i__bat-nx-snooze-f": 0,
        "_____10c-i__bat-cx-de_gen-f": 0,
        "_____10c-i__bat-cx-dstmap-d": {"t_mbbb": [["to_first_block", [1, 1, 1], 1, False]]}
   }
}
