# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protocol/common.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'protocol/common.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15protocol/common.proto\x12\x0e\x66\x65\x61gi.protocol\"R\n\x0eProtocolHeader\x12/\n\x0bprotocol_id\x18\x01 \x01(\x0e\x32\x1a.feagi.protocol.ProtocolID\x12\x0f\n\x07version\x18\x02 \x01(\r\"\x1c\n\tTimestamp\x12\x0f\n\x07time_ms\x18\x01 \x01(\x04*>\n\nProtocolID\x12\x14\n\x10UNKNOWN_PROTOCOL\x10\x00\x12\x07\n\x03\x46\x43P\x10\x01\x12\x07\n\x03\x46VP\x10\x02\x12\x08\n\x04\x46SMP\x10\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protocol.common_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PROTOCOLID']._serialized_start=155
  _globals['_PROTOCOLID']._serialized_end=217
  _globals['_PROTOCOLHEADER']._serialized_start=41
  _globals['_PROTOCOLHEADER']._serialized_end=123
  _globals['_TIMESTAMP']._serialized_start=125
  _globals['_TIMESTAMP']._serialized_end=153
# @@protoc_insertion_point(module_scope)
