# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protocol/fsmp.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'protocol/fsmp.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from protocol import common_pb2 as protocol_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13protocol/fsmp.proto\x12\x0e\x66\x65\x61gi.protocol\x1a\x15protocol/common.proto\"\xdd\x01\n\x0b\x46SMPMessage\x12.\n\x06header\x18\x01 \x01(\x0b\x32\x1e.feagi.protocol.ProtocolHeader\x12-\n\x04type\x18\x02 \x01(\x0e\x32\x1f.feagi.protocol.FSMPMessageType\x12\x33\n\x0csensory_data\x18\x03 \x01(\x0b\x32\x1b.feagi.protocol.SensoryDataH\x00\x12/\n\nmotor_data\x18\x04 \x01(\x0b\x32\x19.feagi.protocol.MotorDataH\x00\x42\t\n\x07payload\"\xd1\x01\n\x0bSensoryData\x12\x12\n\nchannel_id\x18\x01 \x01(\r\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\x12?\n\nproperties\x18\x03 \x03(\x0b\x32+.feagi.protocol.SensoryData.PropertiesEntry\x12,\n\ttimestamp\x18\x04 \x01(\x0b\x32\x19.feagi.protocol.Timestamp\x1a\x31\n\x0fPropertiesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\xcd\x01\n\tMotorData\x12\x12\n\nchannel_id\x18\x01 \x01(\r\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\x12=\n\nproperties\x18\x03 \x03(\x0b\x32).feagi.protocol.MotorData.PropertiesEntry\x12,\n\ttimestamp\x18\x04 \x01(\x0b\x32\x19.feagi.protocol.Timestamp\x1a\x31\n\x0fPropertiesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01*a\n\x12SensoryChannelType\x12\x13\n\x0fUNKNOWN_SENSORY\x10\x00\x12\n\n\x06VISION\x10\x01\x12\t\n\x05\x41UDIO\x10\x02\x12\x12\n\x0ePROPRIOCEPTION\x10\x03\x12\x0b\n\x07TACTILE\x10\x04*Q\n\x10MotorChannelType\x12\x11\n\rUNKNOWN_MOTOR\x10\x00\x12\x0c\n\x08MOVEMENT\x10\x65\x12\n\n\x06SPEECH\x10\x66\x12\x10\n\x0cMANIPULATION\x10g*E\n\x0f\x46SMPMessageType\x12\x10\n\x0c\x46SMP_UNKNOWN\x10\x00\x12\x10\n\x0c\x46SMP_SENSORY\x10\x01\x12\x0e\n\nFSMP_MOTOR\x10\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protocol.fsmp_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SENSORYDATA_PROPERTIESENTRY']._loaded_options = None
  _globals['_SENSORYDATA_PROPERTIESENTRY']._serialized_options = b'8\001'
  _globals['_MOTORDATA_PROPERTIESENTRY']._loaded_options = None
  _globals['_MOTORDATA_PROPERTIESENTRY']._serialized_options = b'8\001'
  _globals['_SENSORYCHANNELTYPE']._serialized_start=706
  _globals['_SENSORYCHANNELTYPE']._serialized_end=803
  _globals['_MOTORCHANNELTYPE']._serialized_start=805
  _globals['_MOTORCHANNELTYPE']._serialized_end=886
  _globals['_FSMPMESSAGETYPE']._serialized_start=888
  _globals['_FSMPMESSAGETYPE']._serialized_end=957
  _globals['_FSMPMESSAGE']._serialized_start=63
  _globals['_FSMPMESSAGE']._serialized_end=284
  _globals['_SENSORYDATA']._serialized_start=287
  _globals['_SENSORYDATA']._serialized_end=496
  _globals['_SENSORYDATA_PROPERTIESENTRY']._serialized_start=447
  _globals['_SENSORYDATA_PROPERTIESENTRY']._serialized_end=496
  _globals['_MOTORDATA']._serialized_start=499
  _globals['_MOTORDATA']._serialized_end=704
  _globals['_MOTORDATA_PROPERTIESENTRY']._serialized_start=447
  _globals['_MOTORDATA_PROPERTIESENTRY']._serialized_end=496
# @@protoc_insertion_point(module_scope)
