version: "3"

networks:
  tb:
    driver: bridge

services:
#  ros:
#    build: ../third_party/ros/
#    # stdin_open: true
#    # tty: true
#    networks:
#      - tb

  feagi:
    build: ./
    environment:
      - CONTAINERIZED=true
      - influxdb=true
    networks:
      - tb
    depends_on:
      - influxdb

  influxdb:
#    image: library/influxdb:2.0.7-alpine
    build: ../third_party/influxdb/
    environment:
      - CONTAINERIZED=true
    networks:
      - tb
