version: "3"

services:
  mongo:
    image: mongo:latest
    volumes:
      - ./mongodb:/data/db
    networks:
      - db_net

  influx:
    image: influxdb:latest
    volumes:
      - ./influxdb:/var/lib/influxdb
    networks:
      - db_net

  feagi:
    build: .  
    depends_on:
      - influx
      - mongo
    networks:
      - db_net

networks:
  db_net:
    driver: bridge

ros:
    build:
      context: ./
      dockerfile: Dockerfile.ros
    ports:
      - "6080:80"
      - "2000"
    privileged: true
    devices:
      - "/dev:/dev"
    networks:
      - tb_net
