version: "3"

networks:
  net:
    driver: bridge

services:
  ros_gazebo:
    build: ../third_party/gazebo/smart_car/
    deploy:
      resources:
        limits:
          cpus: '2'
    ports:
      - "6080:80"
     #environment:
     #  - OPENBOX_ARGS='--startup "/opt/source-code/freenove_4wd_car_description/setup_container.sh"'
    privileged: true
    # stdin_open: true
    # tty: true
    networks:
      - net
      
  godot:
    build: ../third_party/godot/container
    ports:
      - "6081:80"
    privileged: true
    # stdin_open: true
    # tty: true
    networks:
      - net

  feagi:
    build: ./
    privileged: true
    environment:
      - GAZEBO_CONTAINER=true
      - "PYTHONUNBUFFERED=1"
    ports:
      - 30003:30003
    networks:
      - net
