version: "3"

networks:
  net:
    driver: bridge

services:
  ros_gazebo:
    build: ../third_party/gazebo/smart_car/
    deploy:
      resources:
        limits:
          cpus: '2'
    ports:
      - "127.0.0.1:6080:80"
     #environment:
     #  - OPENBOX_ARGS='--startup "/opt/source-code/freenove_4wd_car_description/setup_container.sh"'
    privileged: true
    # stdin_open: true
    # tty: true
    networks:
      - net
    expose:
      - "30003"

  feagi:
    build: ./
    privileged: true
    environment:
      - GAZEBO_CONTAINER=true
      - "PYTHONUNBUFFERED=1"
    networks:
      - net

