version: "3"

networks:
  net:
    driver: bridge

services:
  ros:
    build: ../3rd_party/ros/Micro-ROS
    # stdin_open: true
    # tty: true
    networks:
      - net

  feagi:
    build: ./
    environment:
      - CONTAINERIZED=true
    networks:
      - net