version: "3"

networks:
  tb:
    driver: bridge

services:
  ros:
    build: ../third_party/ros/
    # stdin_open: true
    # tty: true
    networks:
      - tb

  feagi:
    build: ./
    environment:
      - CONTAINERIZED=true
    networks:
      - tb

  mongodb:
    build: ../third_party/mongodb/
    environment:
      - CONTAINERIZED=true
    networks:
      - tb

  influxdb:
    build: ../third_party/influxdb/
    environment:
      - CONTAINERIZED=true
    networks:
      - tb
