version: "3"

networks:
  net:
    driver: bridge

services:
  godot:
    build: ../third_party/godot/
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '2g'
    ports:
      - "6081:8080"
      - "9050:9050"
      - "30001:30001" # ZMQ port for feagi to connect for Gadot
    env_file:
      - ./.env
    privileged: true
    networks:
      - net
    depends_on:
      - feagi

  feagi:
    build: ./
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '2g'
    ports:
      - "8000:8000"
      - "30000:30000"
      - "30010:30010" # ZMQ Port for Agent to Connect to Feagi
    env_file:
      - ./.env
    volumes:
      - ../src/:/opt/source-code/feagi/src
    networks:
      - net


# docker compose -f feagi-OnlyGodot.yml up --build