version: "3"

networks:
  net:
    driver: bridge

services:
  influxdb:
    image: influxdb:2.0.7
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '2g'
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=$INFLUXDB_MODE
      - DOCKER_INFLUXDB_INIT_RETENTION=$INFLUXDB_RETENTION
      - DOCKER_INFLUXDB_INIT_USERNAME=$INFLUXDB_USERNAME
      - DOCKER_INFLUXDB_INIT_PASSWORD=$INFLUXDB_PASSWORD
      - DOCKER_INFLUXDB_INIT_ORG=$INFLUXDB_ORG
      - DOCKER_INFLUXDB_INIT_BUCKET=$INFLUXDB_BUCKET
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=$INFLUXDB_TOKEN
    ports:
      - 8086:8086
    volumes:
      - influxdb_data:/var/lib/influxdb
    healthcheck:
      test: "exit 0"
    networks:
      - net

        
  ros-gazebo:
    build:
      context: ../third_party/gazebo/feagi_robot
      dockerfile: Dockerfile.M1
    deploy:
      resources:
        limits:
          cpus: '8'
          memory: '2g'
    ports:
      - "6080:80"
    privileged: false
    networks:
      - net

  godot:
    build: ../third_party/godot/
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '2g'
    ports:
      - "6081:8080"
      - "9050:9050"
    privileged: true
    networks:
      - net

  grafana:
    build: ../third_party/grafana/
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '2g'
    environment:
      - INFLUXDB_USER=$INFLUXDB_USERNAME
      - INFLUXDB_PASSWORD=$INFLUXDB_PASSWORD
      - INFLUXDB_TOKEN=$INFLUXDB_TOKEN
      - INFLUXDB_ORG=$INFLUXDB_ORG
      - INFLUXDB_BUCKET=$INFLUXDB_BUCKET
    ports:
      - 6082:3000
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - net

  feagi:
    build: ./
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '2g'
    ports:
      - "8000:8000"
      - "30000:30000"
    environment:
      - CONTAINERIZED=true
      - PYTHONUNBUFFERED=1
    volumes:
      - ../src/:/opt/source-code/feagi/src
    networks:
      - net

  gui:
    build: ../src/gui/
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '2g'
    ports:
      - "3000:3000"
    networks:
      - net

volumes:
  grafana_data:
  influxdb_data:
