version: "3"

networks:
  net:
    driver: bridge

services:
  ros-gazebo:
    build: 
      context: ../third_party/gazebo/smart_car/
      dockerfile: low_res_Dockerfile
    deploy:
      resources:
        limits:
          cpus: '2'
    ports:
      - "6080:80"
    privileged: false
    networks:
      - net

  godot:
    build: ../third_party/godot/
    ports:
      - "6081:8080"
      - "9050:9050"
    privileged: true
    networks:
      - net

  feagi:
    build: ./
    ports:
      - "8000:8000"
    environment:
      - CONTAINERIZED=true
      - PYTHONUNBUFFERED=1
    volumes:
      - ../src/evo/static_genome.json:/opt/source-code/feagi/src/evo/static_genome.json
      - ../src/feagi_configuration.ini:/opt/source-code/feagi/src/feagi_configuration.ini
    networks:
      - net

  gui:
    build: ../src/gui/
    ports:
      - "3000:3000"
    networks:
      - net
