version: "3"

services:
  ros-gazebo:
    build: ../third_party/physical_robots/elecfreaks/
    privileged: true
    network_mode: host
    ports:
      - "6080:80"
    environment:
      - DOCKER_COMPUTER_MAC_ADDRESS=xx:xx:xx:xx:xx:xx
      - DOCKER_MICROBIT_MAC_ADDRESS=xx:xx:xx:xx:xx:xx

  godot:
    build: ../third_party/godot/
    ports:
      - "6081:8080"
      - "9050:9050"
    privileged: true
    network_mode: host


  feagi:
    build: ./
    ports:
      - "8000:8000"
    network_mode: host
    environment:
      - CONTAINERIZED=true
      - PYTHONUNBUFFERED=1
    volumes:
      - ../src/evo/static_genome.py:/opt/source-code/feagi/src/evo/static_genome.py
      - ../src/feagi_configuration.ini:/opt/source-code/feagi/src/feagi_configuration.ini

  gui:
    build: ../src/gui/
    ports:
      - "3000:3000"
    network_mode: host
