genome = {
    'version': "2.0",
    "max_burst_count": 3,
    "evolution_burst_count": 50,
    'neighbor_locator_rule': {'rule_0': {'param_1': 0, 'param_2': 0},
                              'rule_1': {'param_1': 1, 'param_2': 1},
                              'rule_10': {'param_1': 1, 'param_2': 1},
                              'rule_11': {'param_1': 1, 'param_2': 1},
                              'rule_12': {'param_1': 1, 'param_2': 1},
                              'rule_13': {'param_1': 1, 'param_2': 1},
                              'rule_14': {'param_1': 1, 'param_2': 1},
                              'rule_15': {'param_1': 1, 'param_2': 1},
                              'rule_16': {'param_1': 1, 'param_2': 1},
                              'rule_17': {'param_1': 1, 'param_2': 1},
                              'rule_18': {'param_1': 1, 'param_2': 1},
                              'rule_19': {'param_1': 1, 'param_2': 1},
                              'rule_2': {'param_1': 5, 'param_2': 5, 'param_3': 3},
                              'rule_3': {'param_1': 3, 'param_2': 3},
                              'rule_4': {'param_1': 3, 'param_2': 3},
                              'rule_5': {'param_1': 3,
                                         'param_2': 3,
                                         'param_3': 3,
                                         'param_4': 3,
                                         'param_5': 3,
                                         'param_6': 3,
                                         'param_7': 3},
                              'rule_6': {'param_1': 1, 'param_2': 1},
                              'rule_7': {'param_1': 1, 'param_2': 1},
                              'rule_9': {'param_1': 1, 'param_2': 1}},
    "species": {
        "parents": {},
        "species_id": "",
        "class": "toy",
        "brand": "gazebo",
        "model": "smart_car"
    },
    "blueprint": {
        "_____10b-_____s-__-__name-t":  "smart_car",

        "_____10c-i__bat-cx-__name-t":  "battery_ipu",
        "_____10c-i__bat-cx-_group-t":  "IPU",
        "_____10c-i__bat-cx-_n_cnt_i":  500,
        "_____10c-i__bat-cx-gd_vis-b":  True,
        "_____10c-i__bat-nx-rcordx-i":  100,
        "_____10c-i__bat-nx-rcordy-i":  0,
        "_____10c-i__bat-nx-rcordz-i":  0,
        "_____10c-i__bat-nx-___bbx-i":  1,
        "_____10c-i__bat-nx-___bby-i":  1,
        "_____10c-i__bat-nx-___bbz-i":  10,
        "_____10c-i__bat-cx-__rand-b":  True,
        "_____10c-i__bat-cx-synatt-i":  100,
        "_____10c-i__bat-cx-init_s-b":  False,
        "_____10c-i__bat-cx-pstcr_-f":  50000,
        "_____10c-i__bat-cx-pstcrm-f":  35,
        "_____10c-i__bat-cx-plst_c-f":  0.05,
        "_____10c-i__bat-nx-fire_t-f":  1,
        "_____10c-i__bat-nx-refrac-i":  0,
        "_____10c-i__bat-nx-leak_c-f":  0,
        "_____10c-i__bat-nx-c_fr_c-i":  3,
        "_____10c-i__bat-nx-snooze-f":  0,
        "_____10c-i__bat-nx-geo_x0-f":  0,
        "_____10c-i__bat-nx-geo_x1-f":  10,
        "_____10c-i__bat-nx-geo_y0-f":  0,
        "_____10c-i__bat-nx-geo_y1-f":  10,
        "_____10c-i__bat-nx-geo_z0-f":  0,
        "_____10c-i__bat-nx-geo_z1-f":  100,
        "_____10c-i__bat-cx-dstmap-d":  {"o__mot": ["rule_6", "param_2"]},

        "_____10c-o__mot-cx-__name-t": "motor_opu",
        "_____10c-o__mot-cx-_group-t": "OPU",
        "_____10c-o__mot-cx-_n_cnt_i": 1000,
        "_____10c-o__mot-cx-gd_vis-b": True,
        "_____10c-o__mot-nx-rcordx-i": 20,
        "_____10c-o__mot-nx-rcordy-i": 0,
        "_____10c-o__mot-nx-rcordz-i": 0,
        "_____10c-o__mot-nx-___bbx-i": 4,
        "_____10c-o__mot-nx-___bby-i": 1,
        "_____10c-o__mot-nx-___bbz-i": 20,
        "_____10c-o__mot-cx-__rand-b": True,
        "_____10c-o__mot-cx-synatt-i": 100,
        "_____10c-o__mot-cx-init_s-b": False,
        "_____10c-o__mot-cx-pstcr_-f": 500,
        "_____10c-o__mot-cx-pstcrm-f": 35,
        "_____10c-o__mot-cx-plst_c-f": 0.05,
        "_____10c-o__mot-nx-fire_t-f": 1,
        "_____10c-o__mot-nx-refrac-i": 0,
        "_____10c-o__mot-nx-leak_c-f": 0,
        "_____10c-o__mot-nx-c_fr_c-i": 3,
        "_____10c-o__mot-nx-snooze-f": 0,
        "_____10c-o__mot-nx-geo_x0-f": 0,
        "_____10c-o__mot-nx-geo_x1-f": 40,
        "_____10c-o__mot-nx-geo_y0-f": 0,
        "_____10c-o__mot-nx-geo_y1-f": 10,
        "_____10c-o__mot-nx-geo_z0-f": 0,
        "_____10c-o__mot-nx-geo_z1-f": 200,
        "_____10c-o__mot-cx-dstmap-d":  {"o__mot": ["rule_1", "param_1"]}
    }
}
