version: "3"

networks:
  net:
    driver: bridge

services:
  ros-gazebo:
    build: ../third_party/gazebo/smart_car/
    deploy:
      resources:
        limits:
          cpus: '2'
    ports:
      - "6080:80"
    privileged: true
    networks:
      - net

  feagi:
    build: ./
    environment:
      - CONTAINERIZED=true
      - "PYTHONUNBUFFERED=1"
    networks:
      - net

  mongodb:
    image: mongo:5.0.0-rc4-focal
    restart: always
    ports:
      - "27017:27017"
    environment:
      - CONTAINERIZED=true
    volumes:
      - ./data:/data/db
    networks:
      - net
