version: "3"

networks:
  tb:
    driver: bridge

services:
  ros:
    build: ../third_party/ros/
    # stdin_open: true
    # tty: true
    networks:
      - tb

  feagi:
    build: ./
    environment:
      - CONTAINERIZED=true
    networks:
      - tb

  mongodb:
    image: mongo:5.0.0-rc4-focal
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
      - CONTAINERIZED=true
    networks:
      - tb
