version: "3"

networks:
  net:
    driver: bridge

services:
  ros:
    build: ../third_party/ros/Micro-ROS
    # stdin_open: true
    privileged: true
    tty: true
    devices:
      - "/dev:/dev"
    networks:
      - net

  feagi:
    build: ./
    environment:
      - CONTAINERIZED=true
    networks:
      - net