version: "3"

services:
  ros:
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - "2000"
    # stdin_open: true
    # tty: true
    # networks:
    #   - tb_net

  feagi:
    build:
      context: ./
      dockerfile: ../../docker/Dockerfile
    # networks:
    #   - tb_net

# networks:
#   tb_net:
#     driver: bridge
