version: "3"

services:
  ros:
    build:
      context: ./
      dockerfile: Dockerfile.ros
    environment:
      - TURTLEBOT3_MODEL=waffle_pi
    command: >
      /bin/bash -c "source ros2_ws/install/setup.bash && 
        ros2 launch turtlebot3_gazebo turtlebot3_world.launch.py && 
        ros2 run py_topic py_laser_scan && 
        ros2 run turtlebot3_teleop teleop_keyboard"
    networks:
      - tb_net

  feagi:
    build:
      context: ./
      dockerfile: Dockerfile.feagi
    depends_on: 
      - ros
    networks:
      - tb_net

networks:
  tb_net:
    driver: bridge
