version: "3"

networks:
  tb:
    driver: bridge

services:
  ros:
    build:
      context: ./
      dockerfile: ./Dockerfile
    # stdin_open: true
    # tty: true
    networks:
      - tb

  feagi:
    build:
      context: ./
      dockerfile: ../../docker/Dockerfile
    tty: True
    ports:
      - "21000"
    networks:
      - tb
