version: "3"

services:
  ros:
    build:
      context: ./
      dockerfile: Dockerfile.ros
    ports:
      - "6080:80"
      - "2000"
    devices:
      - "/dev/ttyACM0:/dev/ttyACM0"
    networks:
      - tb_net

  feagi:
    build:
      context: ./
      dockerfile: ../../docker/Dockerfile
    depends_on: 
      - ros
    logging:
      driver: "none"
    ports:
      - "2000"
    networks:
      - tb_net

networks:
  tb_net:
    driver: bridge
