name: Contribute to public FEAGI

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '.github/workflows/**'
    branches:
      - pre-pub-staging

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Check out Neuraville code
      uses: actions/checkout@v4
      with:
        sparse-checkout: .
        fetch-depth: 0
        path: neuraville-feagi

    - name: Generate branch name
      run: echo "BRANCH_NAME=neuraville-$(date +'%Y-%m-%d-%H-%M-%S')" >> $GITHUB_ENV

    - name: Checkout or create neuraville branch
      run: |
        cd neuraville-feagi
        git checkout $BRANCH_NAME || git checkout -b $BRANCH_NAME

    - name: Check out Community code
      uses: actions/checkout@v4
      with:
        sparse-checkout: .
        fetch-depth: 0
        path: community-feagi

    - name: Setup Git with PAT and commit changes
      run: |
        git config --global user.email "dev@neuraville.com"
        git config --global user.name "NeuravilleDeveloper"
        git remote | grep public && git remote remove public
        git remote add public https://github.com/feagi/feagi.git
        git diff --exit-code || git commit -m "Sync with pre-pub-staging excluding .env and .github directory changes"
        git push public ${{ env.BRANCH_NAME }}

    - name: Create PR using GitHub CLI
      run: |
        # Set up GitHub CLI
        gh auth login --with-token <<< "${{ secrets.PUBLIC_PAT_MNT }}"
        
        # Create a pull request
        gh pr create \
          --repo feagi/feagi \
          --base staging \
          --head ${{ env.BRANCH_NAME }} \
          --title "Updates from Neuraville Inc" \
          --body "This PR syncs with latest Neuraville Inc. development code."
      env:
        GH_CLI_TOKEN: ${{ secrets.PUBLIC_PAT_MNT }}
