name: Update Javascript Webcam Hub

on:
  push:
    branches:
      - "main"
    paths:
      - '!third_party/embodiments/neuraville/javascript_webcam/version.py'
      - 'third_party/embodiments/neuraville/javascript_webcam/**'


jobs:
  docker:
    runs-on: ubuntu-latest
    if: github.repository == 'feagi/feagi'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Merge in New Changes
        run: |
          # Set up Git
          git config --global user.name "BrainVisualizerPushAction"
          git config --global user.email "BrainVisualizerPushAction@neuraville.com"
          git config --global --add safe.directory /__w/brain-visualizer/brain-visualizer
          echo "set vars"
          git checkout -b temp
      - name: Update Dockerfile and version
        run: |
          export FEAGI_PATH=$(pwd)
          cd third_party/embodiments/neuraville/javascript_webcam/
          bash $FEAGI_PATH/generate_version.sh
          if [ -f Dockerfile ]; then
              sed -e 's|COPY controller.py /root/|COPY controller.py /root/|' \
                  -e 's|COPY configuration.py /root/|COPY configuration.py /root/|' \
                  -e 's|COPY version.py /root/|COPY version.py /root/|' \
                  "Dockerfile" > "NewDockerfile"
          fi
          mv NewDockerfile Dockerfile
      - name: Push version changes
        run: |
          git add .
          git commit -m "Updated Version"
          echo "committed"
          git push origin temp:version --force
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: List Files
        run: |
          ls third_party/embodiments/neuraville/javascript_webcam
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: third_party/embodiments/neuraville/javascript_webcam
          platforms: linux/amd64,linux/arm64
          push: true
          tags: neuraville/webcam_controller:latest
