name: Update FEAGI on Docker Hub

on:
  push:
    branches:
      - "main"
    paths:
      - 'src/**'
      - 'generate_version.sh'


jobs:
  docker:
    runs-on: ubuntu-latest
    if: github.repository == 'feagi/feagi'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: docker/
          platforms: linux/amd64,linux/arm64
          push: true
          tags: neuraville/feagi:latest
