name: Push to feagi/feagi

on:
  push:
    paths-ignore:
      - '.github/workflows/NV_*.yml'
    branches:
      - pre-pub-staging
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.FEAGI_PAT5 }}

    - name: Generate branch name
      run: echo "BRANCH_NAME=neuraville-$(date +'%Y-%m-%d-%H-%M-%S')" >> $GITHUB_ENV


    - name: Unstage .env changes
      run: git restore --source=HEAD --staged ./docker/.env

    - name: Setup Git with PAT
      run: |
        git config --global user.email "dev@neuraville.com"
        git config --global user.name "NeuravilleDeveloper"
        git remote add public https://x-access-token:${{ secrets.FEAGI_PAT5 }}@github.com/feagi/feagi.git

    - name: Fetch latest from public repo and merge with allow unrelated histories
      run: |
        git fetch public
        git merge public/staging --allow-unrelated-histories || true

    - name: Resolve .env conflict favoring remote version
      run: |
        git checkout --theirs ./docker/.env
        git add ./docker/.env
        git commit -m "Resolved .env conflict favoring remote version"

    - name: Unstage .github directory changes
      run: git restore --source=HEAD --staged .github/

    - name: Checkout or create neuraville branch
      run: |
        git checkout $BRANCH_NAME || git checkout -b $BRANCH_NAME

    - name: Pull latest changes from neuraville branch on public repo
      run: |
        git pull public $BRANCH_NAME || true

    - name: Commit other changes and push to public repo
      run: |
        git diff --exit-code || git commit -m "Sync with pre-pub-staging excluding .env and .github directory changes"
        git push public $BRANCH_NAME --force

    - name: Create PR on feagi/feagi repo
      uses: repo-sync/pull-request@v2
      with:
        destination_repository: "feagi/feagi"
        source_branch: $BRANCH_NAME
        destination_branch: "staging"
        pr_title: "Updates from Neuraville Inc"
        pr_body: "This PR syncs with latest Neuraville Inc. development code."
        pr_label: "sync"
        github_token: ${{ secrets.FEAGI_PAT5 }}

