name: PushToGCR
on:
  [workflow_dispatch]

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
    - name: Download FEAGI
      uses: actions/checkout@v2

    - name: Push to GCR GitHub Action
      uses: RafikFarhad/push-to-gcr-github-action@v4.1
      with:
        gcloud_service_key: ${{secrets.GCR_SERVICE}}
        project_id: feagi-poc
        image_name: feagi/feagi
        image_tag: $(date +%s)
        dockerfile: docker/Dockerfile
