name: Push to feagi/feagi

on:
  push:
    branches:
      - pre-pub-staging
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Unstage .env changes
      run: git restore --source=HEAD --staged ./docker/.env

    - name: Setup Git with PAT
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git remote add public https://github.com/feagi/feagi.git

    - name: Commit changes without .env and push to public repo
      run: |
        git checkout -b neuraville
        git diff --exit-code || git commit -m "Sync with pre-pub-staging excluding .env"
        git push public neuraville

    - name: Create PR on feagi/feagi repo
      uses: repo-sync/pull-request@v2
      with:
        source_repo: "Neuraville/feagi"
        destination_repo: "feagi/feagi"
        source_branch: "neuraville"
        destination_branch: "staging"
        pr_title: "Sync with Neuraville pre-pub-staging"
        pr_body: "This PR syncs with the latest changes from the Neuraville pre-pub-staging branch."
        pr_label: "sync"
        github_token: ${{ secrets.FEAGI_PAT }}
