name: PushToGCR
on:
  [workflow_dispatch]

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
    - name: Download FEAGI
      uses: actions/checkout@v2
    
    # This step seems rather inefficient. Too bad!
    - name: Build and tag FEAGI
      run: docker build docker/ --file docker/Dockerfile --tag gcr.io/feagi-poc/feagi/feagi:${{vars.GITHUB_RUN_ATTEMPT}}

    - name: Login into Google
      # we need to authenticate with google cloug first
      uses: google-github-actions/setup-gcloud@v1.1.1
      with:
        service_account_key: ${{secrets.GCR_SERVICE}}
        project_id: feagi-poc
        export_default_credentials: true

    - name: Push Docker Image to Google
      run: docker push gcr.io/feagi-poc/feagi/feagi:${{vars.GITHUB_RUN_ATTEMPT}}
