name: PushToGCR
on:
  [workflow_dispatch]

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
    - name: Download FEAGI
      uses: actions/checkout@v2

    # This step seems rather inefficient. Too bad!
    - name: Build and tag FEAGI
      run: docker build /docker/ --file /docker/Dockerfile --tag ${{secrets.host}}/${{secrets.projectName}}/feagi:$(date +%s)

    - name: Login into Google
      # we need to authenticate with google cloug first
      uses: google-github-actions/setup-gcloud@master
      with:
        service_account_key: ${{secrets.serviceAccountKey}}
        project_id: ${{secrets.projectName}}
        export_default_credentials: true

    - name: Push Docker Image to Google
      run: docker push gcr.io/{{secrets.projectName}}/feagi:$(date +%s)
