name: PushToGCR
on:
  [workflow_dispatch]

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
    - name: Download FEAGI
      uses: actions/checkout@v2
    
    - name: check var
      run: echo ${{ github.run_attempt }}
      
    # This step seems rather inefficient. Too bad!
    - name: Build and tag FEAGI
      run: docker build docker/ --file docker/Dockerfile --tag gcr.io/feagi-poc/feagi/feagi:${{ github.run_attempt }}

    - name: Push to GCR GitHub Action
      uses: RafikFarhad/push-to-gcr-github-action@v4.1
      with:
        gcloud_service_key: ${{secrets.GCR_SERVICE}}
        project_id: feagi
        image_name: feagi
        image_tag: ${{ github.run_attempt }}
