name: Sync
on:
  [workflow_dispatch]

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
    - name: Download FEAGI
      uses: actions/checkout@v2
      with:
        repository: feagi/feagi
    
    - name: Set Origin
      run: git remote set-url --add --push origin https://${{secrets.LOCALUSERNAME}}:${{secrets.LOCALTOKEN}}@github.com/Neuraville/NRS-FEAGI.git
      
    - name: Push FEAGI
      run: git push -u origin staging
