name: Update dev gcr FEAGI
on:
  push:
    branches:
      - staging
    paths:
      - 'src/**'
      - 'generate_version.sh'
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
    - name: testing
      run: |
        ls
