name: Create a PR contain versions

on:
  workflow_dispatch:
  push:
    branches:
      - "pre-release"

jobs:
  PR_to_main:
    - name: Create PR using GitHub CLI
      run: |
        # Set up GitHub CLI
        gh auth login --with-token <<< "${{ secrets.PUBLIC_PAT_MNT }}"
        
        # Create a pull request
        gh pr create \
          --repo feagi/feagi \
          --base pre-release \
          --head main \
          --title "Updates versions along with new changes" \
          --body "This PR syncs with latest Neuraville Inc. development code."
      env:
        GH_CLI_TOKEN: ${{ secrets.PUBLIC_PAT_MNT }}
