name: Create a PR contain versions

on:
  create:
    branches:
      - 'pre-release'
    push:
      branches:
        - 'pre-release'
  workflow_dispatch:

jobs:
  PR_to_main:
    runs-on: ubuntu-latest
    if: github.repository == 'feagi/feagi'
    steps:
    - name: Create PR using GitHub CLI
      run: |
        # Set up GitHub CLI
        gh auth login --with-token <<< "${{ secrets.GITHUB_TOKEN }}"
        
        # Create a pull request
        gh pr create \
          --repo feagi/feagi \
          --base main \
          --head pre-release \
          --title "Updates versions along with new changes" \
          --body "This PR syncs with latest Neuraville Inc. development code."
      env:
        GH_CLI_TOKEN: ${{ secrets.GITHUB_TOKEN }}
